// 热门歌手列表
export const HOTARTISTLIST = "HOTARTISTLIST"

// 热门歌手列表
export const HOTARTISTSONGLIST = "HOTARTISTSONGLIST"

// 歌手专辑
export const ALBUMARTISTSONGLIST = "AlbumARTISTSONGLIST"
// 歌手MV
export const MVARTISTSONGLIST = "MVARTISTSONGLIST"
// 歌手描述
export const DESCARTISTSONGLIST = "DESCARTISTSONGLIST"
